// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-nJXOZGVdj6LluPo3T0Qyq6HtckZTyxg',
    appId: '1:90323946057:web:6a2be5fbe6b7d47db40d98',
    messagingSenderId: '90323946057',
    projectId: 'daemon-ca106',
    authDomain: 'daemon-ca106.firebaseapp.com',
    storageBucket: 'daemon-ca106.firebasestorage.app',
    measurementId: 'G-ZQ84VVRJ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbv0eQu5viP-hOayOZmLlCmLZaReqDCo',
    appId: '1:90323946057:android:9666d0cf795bbce0b40d98',
    messagingSenderId: '90323946057',
    projectId: 'daemon-ca106',
    storageBucket: 'daemon-ca106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oWXpi8ddvNusSj5KUVgkMIXVpMnxabk',
    appId: '1:90323946057:ios:52251448b36795eab40d98',
    messagingSenderId: '90323946057',
    projectId: 'daemon-ca106',
    storageBucket: 'daemon-ca106.firebasestorage.app',
    iosBundleId: 'com.example.iotMonitoDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oWXpi8ddvNusSj5KUVgkMIXVpMnxabk',
    appId: '1:90323946057:ios:52251448b36795eab40d98',
    messagingSenderId: '90323946057',
    projectId: 'daemon-ca106',
    storageBucket: 'daemon-ca106.firebasestorage.app',
    iosBundleId: 'com.example.iotMonitoDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-nJXOZGVdj6LluPo3T0Qyq6HtckZTyxg',
    appId: '1:90323946057:web:6cd9a01eead3abc3b40d98',
    messagingSenderId: '90323946057',
    projectId: 'daemon-ca106',
    authDomain: 'daemon-ca106.firebaseapp.com',
    storageBucket: 'daemon-ca106.firebasestorage.app',
    measurementId: 'G-6JNXW7Z8NM',
  );
}
